/**
 * AI Council Dashboard — Application Logic
 * 
 * Reads JSON report data generated by the engine
 * and populates the dashboard with live data.
 */

// ═══ Page Navigation ═══
function showPage(pageName) {
    document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
    document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));

    const page = document.getElementById('page-' + pageName);
    if (page) page.classList.add('active');

    const nav = document.querySelector(`.nav-item[data-page="${pageName}"]`);
    if (nav) nav.classList.add('active');
}

// ═══ Data Loading ═══
let currentData = null;

async function loadLatestReport() {
    try {
        // Try loading today's report
        const today = new Date().toISOString().split('T')[0];
        const response = await fetch(`../data/reports/council_data_${today}.json`);
        
        if (response.ok) {
            currentData = await response.json();
            renderDashboard(currentData);
            document.getElementById('last-update').textContent = 
                `Updated: ${new Date().toLocaleTimeString()}`;
        } else {
            console.log('No report found for today');
            renderDemoData();
        }
    } catch (error) {
        console.log('Could not load report:', error);
        renderDemoData();
    }
}

function refreshData() {
    loadLatestReport();
}

// ═══ Render Dashboard ═══
function renderDashboard(data) {
    if (!data) return;

    const market = data.market || {};
    const macro = data.macro || {};
    const sector = data.sector || {};
    const results = data.results || [];

    // Set date
    document.getElementById('date-badge').textContent = data.date || 'Today';

    // Regime badge
    const regimeBadge = document.getElementById('regime-badge');
    const regime = macro.regime || 'Neutral';
    regimeBadge.textContent = regime;
    regimeBadge.style.background = regime === 'Bull' ? 'var(--green-dim)' 
        : regime === 'Bear' ? 'var(--red-dim)' : 'var(--yellow-dim)';
    regimeBadge.style.color = regime === 'Bull' ? 'var(--green)' 
        : regime === 'Bear' ? 'var(--red)' : 'var(--yellow)';

    // Top metrics
    renderMetric('metric-vix', market.india_vix, getVixColor(market.india_vix));
    renderMetric('metric-mmi', market.mmi_score, 'var(--purple)');
    renderMetric('metric-sentiment', macro.sentiment_score, getSentimentColor(macro.sentiment_score));

    const multiplier = getPositionMultiplier(market.mmi_score, market.india_vix);
    renderMetric('metric-multiplier', multiplier + '×', 'var(--amber)');

    // VIX status
    const vixStatus = document.getElementById('vix-status');
    if (market.india_vix < 17) {
        vixStatus.textContent = '✅ OK to trade';
        vixStatus.style.color = 'var(--green)';
    } else if (market.india_vix < 22) {
        vixStatus.textContent = '⚡ Elevated';
        vixStatus.style.color = 'var(--yellow)';
    } else {
        vixStatus.textContent = '🔴 Reduce risk';
        vixStatus.style.color = 'var(--red)';
    }

    // MMI label
    const mmiLabel = document.getElementById('mmi-label');
    mmiLabel.textContent = getMmiLabel(market.mmi_score);

    // Signal counts
    const buyCount = results.filter(r => r.action === 'BUY').length;
    const holdCount = results.filter(r => r.action === 'HOLD').length;
    const avoidCount = results.filter(r => r.action === 'AVOID').length;
    document.getElementById('buy-count').textContent = buyCount;
    document.getElementById('hold-count').textContent = holdCount;
    document.getElementById('avoid-count').textContent = avoidCount;

    // Macro assessment
    document.getElementById('macro-reasoning').textContent = 
        macro.reasoning || 'No macro analysis available';

    // Top picks
    renderTopPicks(results);

    // Stocks list
    renderStocksList(results);

    // Sectors
    renderSectors(sector);
}

function renderMetric(elementId, value, color) {
    const el = document.getElementById(elementId);
    if (el) {
        const valueEl = el.querySelector('.metric-value');
        if (valueEl) {
            valueEl.textContent = value || '—';
            valueEl.style.color = color;
        }
    }
}

function renderTopPicks(results) {
    const container = document.getElementById('top-picks');
    if (!results || results.length === 0) {
        container.innerHTML = '<div class="empty-state">Run the engine to see recommendations</div>';
        return;
    }

    container.innerHTML = results.map(r => {
        const actionClass = (r.action || 'hold').toLowerCase();
        const confColor = r.confidence > 70 ? 'var(--green)' 
            : r.confidence > 40 ? 'var(--yellow)' : 'var(--red)';
        const ticker = (r.ticker || '').replace('.NS', '');

        return `
            <div class="pick-card">
                <div class="pick-header">
                    <div>
                        <span class="pick-ticker">${ticker}</span>
                        <span class="pick-action ${actionClass}">${r.action || 'N/A'}</span>
                    </div>
                    <div class="conf-bar-lg">
                        <div class="conf-track-lg">
                            <div class="conf-fill-lg" style="width: ${r.confidence || 0}%; background: ${confColor};"></div>
                        </div>
                        <span class="conf-value" style="color: ${confColor};">${r.confidence || 0}%</span>
                    </div>
                </div>
                <div class="pick-body">
                    <div class="pick-metrics">
                        <div class="pick-metric">
                            <div class="pick-metric-value" style="color: var(--accent);">₹${fmt(r.entry_range_low)}–${fmt(r.entry_range_high)}</div>
                            <div class="pick-metric-label">Entry Range</div>
                        </div>
                        <div class="pick-metric">
                            <div class="pick-metric-value" style="color: var(--red);">${r.stop_loss_pct || 7}%</div>
                            <div class="pick-metric-label">Stop Loss</div>
                        </div>
                        <div class="pick-metric">
                            <div class="pick-metric-value" style="color: var(--green);">₹${fmt(r.target_1)}</div>
                            <div class="pick-metric-label">Target 1</div>
                        </div>
                        <div class="pick-metric">
                            <div class="pick-metric-value" style="color: var(--green);">₹${fmt(r.target_2)}</div>
                            <div class="pick-metric-label">Target 2</div>
                        </div>
                        <div class="pick-metric">
                            <div class="pick-metric-value" style="color: var(--amber);">${r.position_multiplier || 1.0}×</div>
                            <div class="pick-metric-label">Size Mult</div>
                        </div>
                    </div>
                    <div class="pick-reasoning">${r.reasoning || 'No reasoning available'}</div>
                </div>
            </div>
        `;
    }).join('');
}

function renderStocksList(results) {
    const container = document.getElementById('stocks-list');
    if (!results || results.length === 0) {
        container.innerHTML = '<div class="empty-state">No data available. Run the engine first.</div>';
        return;
    }
    // Reuse top picks rendering for now
    container.innerHTML = document.getElementById('top-picks').innerHTML;
}

function renderSectors(sector) {
    const container = document.getElementById('sectors-grid');
    const rankings = sector.sector_rankings || [];

    if (rankings.length === 0) {
        container.innerHTML = '<div class="empty-state">No sector data available.</div>';
        return;
    }

    container.innerHTML = rankings.map((s, i) => {
        const rsColor = s.rs_20d > 0 ? 'var(--green)' : s.rs_20d < -2 ? 'var(--red)' : 'var(--yellow)';
        const strength = s.strength || (s.rs_20d > 0 ? 'strong' : s.rs_20d < -2 ? 'weak' : 'neutral');

        return `
            <div class="sector-card">
                <div>
                    <div class="sector-name">${s.name || 'Unknown'}</div>
                    <div class="sector-rank">Rank #${s.rank || (i + 1)} · ${strength}</div>
                </div>
                <div class="sector-rs" style="color: ${rsColor};">
                    ${s.rs_20d > 0 ? '+' : ''}${(s.rs_20d || 0).toFixed(2)}%
                </div>
            </div>
        `;
    }).join('');
}

// ═══ Demo Data (when no report available) ═══
function renderDemoData() {
    const demoData = {
        date: new Date().toISOString().split('T')[0],
        market: {
            india_vix: 15.4,
            mmi_score: 52,
        },
        macro: {
            regime: 'Neutral',
            sentiment_score: 58,
            reasoning: 'Dashboard loaded — waiting for engine to run. Use `python main.py` to generate today\'s analysis. Market data will appear here after the first run.',
        },
        sector: { sector_rankings: [] },
        results: [],
    };
    renderDashboard(demoData);
    document.getElementById('last-update').textContent = 'Demo mode — run engine for live data';
}

// ═══ Helper Functions ═══
function fmt(num) {
    if (!num && num !== 0) return '—';
    return Math.round(num).toLocaleString('en-IN');
}

function getVixColor(vix) {
    if (vix < 17) return 'var(--green)';
    if (vix < 22) return 'var(--yellow)';
    return 'var(--red)';
}

function getSentimentColor(score) {
    if (score > 70) return 'var(--green)';
    if (score > 40) return 'var(--accent)';
    return 'var(--red)';
}

function getMmiLabel(mmi) {
    if (mmi < 30) return '😰 Extreme Fear';
    if (mmi < 50) return '😟 Fear';
    if (mmi < 70) return '😐 Neutral';
    if (mmi < 85) return '😏 Greed';
    return '🤑 Extreme Greed';
}

function getPositionMultiplier(mmi, vix) {
    if (vix > 22) return 0.5;
    if (mmi < 30) return 1.5;
    if (mmi < 50) return 1.25;
    if (mmi < 70) return 1.0;
    if (mmi < 85) return 0.75;
    return 0.5;
}

// ═══ Init ═══
document.addEventListener('DOMContentLoaded', () => {
    loadLatestReport();
});
